#!/bin/bash

echo "🚀 Скрипт для загрузки Telegram Bot на GitHub"
echo "=============================================="
echo ""

echo "📋 Инструкции по загрузке на GitHub:"
echo ""
echo "1. Перейдите на https://github.com/Dimaosadchuk888/Telegram-Bot"
echo "2. Нажмите 'Add file' -> 'Upload files'"
echo "3. Загрузите следующие файлы:"
echo "   - package.json"
echo "   - package-lock.json"
echo "   - README.md"
echo "   - TESTING.md"
echo "   - DEPLOYMENT.md"
echo "   - ecosystem.config.js"
echo "   - railway.json"
echo "   - .gitignore"
echo "   - src/ (вся папка)"
echo ""
echo "4. НЕ загружайте:"
echo "   - .env (содержит секретные данные)"
echo "   - node_modules/ (слишком большой)"
echo "   - logs/ (локальные логи)"
echo ""
echo "5. Добавьте описание коммита: 'Initial commit: Telegram Farming Bot'"
echo "6. Нажмите 'Commit changes'"
echo ""

echo "🌐 После загрузки на GitHub:"
echo "1. Перейдите на https://railway.app"
echo "2. Войдите через GitHub"
echo "3. Создайте новый проект"
echo "4. Выберите ваш репозиторий Telegram-Bot"
echo "5. Настройте переменные окружения"
echo ""

echo "📝 Переменные окружения для Railway:"
echo "BOT_TOKEN=your_actual_bot_token_here"
echo "NODE_ENV=production"
echo "WEBHOOK_URL=https://your-railway-domain.railway.app/webhook"
echo "PORT=3000"
echo ""

echo "✅ Готово! Следуйте инструкциям выше для деплоя."
